[2022-04-28 15:41:45,005] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: cso_2295_ipo_2_cso_xls.py.log_start3 scheduled__2022-04-27T15:41:00+00:00 [queued]>
[2022-04-28 15:41:45,053] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: cso_2295_ipo_2_cso_xls.py.log_start3 scheduled__2022-04-27T15:41:00+00:00 [queued]>
[2022-04-28 15:41:45,053] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 15:41:45,053] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-04-28 15:41:45,053] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 15:41:45,139] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): log_start3> on 2022-04-27 15:41:00+00:00
[2022-04-28 15:41:45,162] {standard_task_runner.py:52} INFO - Started process 21324 to run task
[2022-04-28 15:41:45,164] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cso_2295_ipo_2_cso_xls.py', 'log_start3', 'scheduled__2022-04-27T15:41:00+00:00', '--job-id', '1381', '--raw', '--subdir', 'DAGS_FOLDER/cso_2295/cso_2295_ipo_2_cso_xls.py', '--cfg-path', '/tmp/tmpwnt__amq', '--error-file', '/tmp/tmpcgpkolh2']
[2022-04-28 15:41:45,164] {standard_task_runner.py:77} INFO - Job 1381: Subtask log_start3
[2022-04-28 15:41:46,267] {logging_mixin.py:109} INFO - Running <TaskInstance: cso_2295_ipo_2_cso_xls.py.log_start3 scheduled__2022-04-27T15:41:00+00:00 [running]> on host 0936e4a14e76
[2022-04-28 15:41:46,696] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cso_2295_ipo_2_cso_xls.py
AIRFLOW_CTX_TASK_ID=log_start3
AIRFLOW_CTX_EXECUTION_DATE=2022-04-27T15:41:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-27T15:41:00+00:00
[2022-04-28 15:41:46,703] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-28 15:41:46,709] {dbapi.py:225} INFO - Running statement: do $$
declare
	q_stream integer;
begin  
	select 1 into q_stream
	from list_flow_log
	where object_flow = 0 and status = 1;
  
	if q_stream > 0 then
		raise exception 'IP-offline - The stream is blocked';
	else 
  		INSERT INTO list_flow_log (object_flow, t_start, status) VALUES(0, NOW(), 1);
	end if;

end $$, parameters: None
[2022-04-28 15:41:47,922] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.RaiseException: IP-offline - The stream is blocked
CONTEXT:  PL/pgSQL function inline_code_block line 10 at RAISE

[2022-04-28 15:41:48,326] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=cso_2295_ipo_2_cso_xls.py, task_id=log_start3, execution_date=20220427T154100, start_date=20220428T154145, end_date=20220428T154148
[2022-04-28 15:41:48,662] {standard_task_runner.py:92} ERROR - Failed to execute job 1381 for task log_start3
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.RaiseException: IP-offline - The stream is blocked
CONTEXT:  PL/pgSQL function inline_code_block line 10 at RAISE

[2022-04-28 15:41:49,140] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-28 15:41:49,230] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-28 15:41:49,235] {dbapi.py:225} INFO - Running statement: update list_flow_log
                set t_end=NOW(), status=3, code_error=3, comment = '*Task*: log_start3'
                where id = 124;, parameters: None
[2022-04-28 15:41:49,238] {dbapi.py:233} INFO - Rows affected: 1
[2022-04-28 15:41:50,157] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
