[2022-04-19 13:37:35,095] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: hook_dag.transfer_xml manual__2022-04-19T13:37:26.191995+00:00 [queued]>
[2022-04-19 13:37:35,105] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: hook_dag.transfer_xml manual__2022-04-19T13:37:26.191995+00:00 [queued]>
[2022-04-19 13:37:35,106] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-19 13:37:35,106] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-04-19 13:37:35,106] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-19 13:37:35,113] {taskinstance.py:1264} INFO - Executing <Task(Postgres2File): transfer_xml> on 2022-04-19 13:37:26.191995+00:00
[2022-04-19 13:37:35,118] {standard_task_runner.py:52} INFO - Started process 14329 to run task
[2022-04-19 13:37:35,121] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'hook_dag', 'transfer_xml', 'manual__2022-04-19T13:37:26.191995+00:00', '--job-id', '414', '--raw', '--subdir', 'DAGS_FOLDER/hook_dag.py', '--cfg-path', '/tmp/tmpc33t3112', '--error-file', '/tmp/tmp53f3wqi3']
[2022-04-19 13:37:35,121] {standard_task_runner.py:77} INFO - Job 414: Subtask transfer_xml
[2022-04-19 13:37:35,169] {logging_mixin.py:109} INFO - Running <TaskInstance: hook_dag.transfer_xml manual__2022-04-19T13:37:26.191995+00:00 [running]> on host 22e04adb6bfa
[2022-04-19 13:37:35,209] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hook_dag
AIRFLOW_CTX_TASK_ID=transfer_xml
AIRFLOW_CTX_EXECUTION_DATE=2022-04-19T13:37:26.191995+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-19T13:37:26.191995+00:00
[2022-04-19 13:37:35,215] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-19 13:37:35,241] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=hook_dag, task_id=transfer_xml, execution_date=20220419T133726, start_date=20220419T133735, end_date=20220419T133735
[2022-04-19 13:37:35,293] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-19 13:37:35,363] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-19 13:37:35,367] {dbapi.py:225} INFO - Running statement: UPDATE list_flow_log
                    SET 
                    q_source=None, 
                    q_target=None, 
                    t_end=NOW(), 
                    status=2, 
                    optional_key='TYPE',
                    comment='None'
                    where id = 16;, parameters: None
[2022-04-19 13:37:35,368] {taskinstance.py:1590} ERROR - Error when executing on_success_callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1588, in _run_finished_callback
    task.on_success_callback(context)
  File "/opt/airflow/dags/hook_dag.py", line 95, in task_success_log
    return log_end.execute(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "none" does not exist
LINE 3:                     q_source=None, 
                                     ^

[2022-04-19 13:37:35,416] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
