[2022-04-19 14:00:07,839] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: hook_dag.transfer_xml manual__2022-04-19T13:59:56.853838+00:00 [queued]>
[2022-04-19 14:00:07,853] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: hook_dag.transfer_xml manual__2022-04-19T13:59:56.853838+00:00 [queued]>
[2022-04-19 14:00:07,853] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-19 14:00:07,854] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-04-19 14:00:07,854] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-19 14:00:07,866] {taskinstance.py:1264} INFO - Executing <Task(Postgres2File): transfer_xml> on 2022-04-19 13:59:56.853838+00:00
[2022-04-19 14:00:07,871] {standard_task_runner.py:52} INFO - Started process 15495 to run task
[2022-04-19 14:00:07,873] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'hook_dag', 'transfer_xml', 'manual__2022-04-19T13:59:56.853838+00:00', '--job-id', '446', '--raw', '--subdir', 'DAGS_FOLDER/hook_dag.py', '--cfg-path', '/tmp/tmpk_8ea7sb', '--error-file', '/tmp/tmptset6lb6']
[2022-04-19 14:00:07,874] {standard_task_runner.py:77} INFO - Job 446: Subtask transfer_xml
[2022-04-19 14:00:07,939] {logging_mixin.py:109} INFO - Running <TaskInstance: hook_dag.transfer_xml manual__2022-04-19T13:59:56.853838+00:00 [running]> on host 22e04adb6bfa
[2022-04-19 14:00:07,991] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hook_dag
AIRFLOW_CTX_TASK_ID=transfer_xml
AIRFLOW_CTX_EXECUTION_DATE=2022-04-19T13:59:56.853838+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-19T13:59:56.853838+00:00
[2022-04-19 14:00:07,998] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-19 14:00:08,030] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=hook_dag, task_id=transfer_xml, execution_date=20220419T135956, start_date=20220419T140007, end_date=20220419T140008
[2022-04-19 14:00:08,058] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-19 14:00:08,103] {taskinstance.py:1590} ERROR - Error when executing on_success_callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1588, in _run_finished_callback
    task.on_success_callback(context)
TypeError: 'PostgresOperator' object is not callable
[2022-04-19 14:00:08,129] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
