[2022-04-06 14:23:40,895] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: my_project.inaccurate scheduled__2022-04-05T00:00:00+00:00 [queued]>
[2022-04-06 14:23:40,912] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: my_project.inaccurate scheduled__2022-04-05T00:00:00+00:00 [queued]>
[2022-04-06 14:23:40,912] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 14:23:40,912] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-04-06 14:23:40,912] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 14:23:40,945] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): inaccurate> on 2022-04-05 00:00:00+00:00
[2022-04-06 14:23:40,948] {standard_task_runner.py:52} INFO - Started process 88 to run task
[2022-04-06 14:23:40,950] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_project', 'inaccurate', 'scheduled__2022-04-05T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/my_project.py', '--cfg-path', '/tmp/tmpexa0bqad', '--error-file', '/tmp/tmpx52bsbfk']
[2022-04-06 14:23:40,950] {standard_task_runner.py:77} INFO - Job 39: Subtask inaccurate
[2022-04-06 14:23:40,996] {logging_mixin.py:109} INFO - Running <TaskInstance: my_project.inaccurate scheduled__2022-04-05T00:00:00+00:00 [running]> on host 13210251e6a6
[2022-04-06 14:23:41,048] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_project
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-04-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-05T00:00:00+00:00
[2022-04-06 14:23:41,048] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-06 14:23:41,049] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-04-06 14:23:41,106] {subprocess.py:85} INFO - Output:
[2022-04-06 14:23:41,130] {subprocess.py:89} INFO - inaccurate
[2022-04-06 14:23:41,130] {subprocess.py:93} INFO - Command exited with return code 0
[2022-04-06 14:23:41,159] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=my_project, task_id=inaccurate, execution_date=20220405T000000, start_date=20220406T142340, end_date=20220406T142341
[2022-04-06 14:23:41,202] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-06 14:23:41,223] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
