[2022-04-05 20:29:40,607] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: my_project.inaccurate scheduled__2022-04-04T00:00:00+00:00 [queued]>
[2022-04-05 20:29:40,618] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: my_project.inaccurate scheduled__2022-04-04T00:00:00+00:00 [queued]>
[2022-04-05 20:29:40,618] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-05 20:29:40,619] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-04-05 20:29:40,619] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-05 20:29:40,631] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): inaccurate> on 2022-04-04 00:00:00+00:00
[2022-04-05 20:29:40,636] {standard_task_runner.py:52} INFO - Started process 391 to run task
[2022-04-05 20:29:40,641] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_project', 'inaccurate', 'scheduled__2022-04-04T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/my_project.py', '--cfg-path', '/tmp/tmpwpdfgue5', '--error-file', '/tmp/tmph1tp_1fb']
[2022-04-05 20:29:40,642] {standard_task_runner.py:77} INFO - Job 13: Subtask inaccurate
[2022-04-05 20:29:40,688] {logging_mixin.py:109} INFO - Running <TaskInstance: my_project.inaccurate scheduled__2022-04-04T00:00:00+00:00 [running]> on host 13210251e6a6
[2022-04-05 20:29:40,733] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_project
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-04-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-04T00:00:00+00:00
[2022-04-05 20:29:40,734] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-05 20:29:40,734] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-04-05 20:29:40,780] {subprocess.py:85} INFO - Output:
[2022-04-05 20:29:40,820] {subprocess.py:89} INFO - inaccurate
[2022-04-05 20:29:40,821] {subprocess.py:93} INFO - Command exited with return code 0
[2022-04-05 20:29:40,890] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=my_project, task_id=inaccurate, execution_date=20220404T000000, start_date=20220405T202940, end_date=20220405T202940
[2022-04-05 20:29:40,933] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-05 20:29:40,963] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
