[2022-04-20 15:38:45,612] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: hook_dag.log_start_1 scheduled__2022-04-20T15:33:33+00:00 [queued]>
[2022-04-20 15:38:45,624] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: hook_dag.log_start_1 scheduled__2022-04-20T15:33:33+00:00 [queued]>
[2022-04-20 15:38:45,624] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-20 15:38:45,624] {taskinstance.py:1244} INFO - Starting attempt 2 of 2
[2022-04-20 15:38:45,624] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-20 15:38:45,632] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): log_start_1> on 2022-04-20 15:33:33+00:00
[2022-04-20 15:38:45,636] {standard_task_runner.py:52} INFO - Started process 22771 to run task
[2022-04-20 15:38:45,638] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'hook_dag', 'log_start_1', 'scheduled__2022-04-20T15:33:33+00:00', '--job-id', '770', '--raw', '--subdir', 'DAGS_FOLDER/hook_dag.py', '--cfg-path', '/tmp/tmpurs9vndr', '--error-file', '/tmp/tmp39npudiz']
[2022-04-20 15:38:45,639] {standard_task_runner.py:77} INFO - Job 770: Subtask log_start_1
[2022-04-20 15:38:45,689] {logging_mixin.py:109} INFO - Running <TaskInstance: hook_dag.log_start_1 scheduled__2022-04-20T15:33:33+00:00 [running]> on host 22e04adb6bfa
[2022-04-20 15:38:45,728] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hook_dag
AIRFLOW_CTX_TASK_ID=log_start_1
AIRFLOW_CTX_EXECUTION_DATE=2022-04-20T15:33:33+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-20T15:33:33+00:00
[2022-04-20 15:38:45,734] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-20 15:38:45,737] {dbapi.py:225} INFO - Running statement: do $$
declare
	q_stream integer;
begin  
	select 1 into q_stream
	from list_flow_log
	where object_flow = 1 and status = 1;
  
	if q_stream > 0 then
		raise exception 'IP-offline - The stream is blocked';
	else 
  		INSERT INTO list_flow_log (object_flow, t_start, status) VALUES(1, NOW(), 1);
	end if;

end $$, parameters: None
[2022-04-20 15:38:45,738] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.RaiseException: IP-offline - The stream is blocked
CONTEXT:  PL/pgSQL function inline_code_block line 10 at RAISE

[2022-04-20 15:38:45,747] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=hook_dag, task_id=log_start_1, execution_date=20220420T153333, start_date=20220420T153845, end_date=20220420T153845
[2022-04-20 15:38:45,755] {standard_task_runner.py:92} ERROR - Failed to execute job 770 for task log_start_1
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.RaiseException: IP-offline - The stream is blocked
CONTEXT:  PL/pgSQL function inline_code_block line 10 at RAISE

[2022-04-20 15:38:45,773] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-20 15:38:45,800] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
