[2022-04-05 21:15:04,989] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: hook_dag.hook_task manual__2022-04-05T21:14:01.741481+00:00 [queued]>
[2022-04-05 21:15:04,999] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: hook_dag.hook_task manual__2022-04-05T21:14:01.741481+00:00 [queued]>
[2022-04-05 21:15:04,999] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-05 21:15:04,999] {taskinstance.py:1244} INFO - Starting attempt 2 of 2
[2022-04-05 21:15:04,999] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-05 21:15:05,009] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): hook_task> on 2022-04-05 21:14:01.741481+00:00
[2022-04-05 21:15:05,013] {standard_task_runner.py:52} INFO - Started process 911 to run task
[2022-04-05 21:15:05,015] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'hook_dag', 'hook_task', 'manual__2022-04-05T21:14:01.741481+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/hook_dag.py', '--cfg-path', '/tmp/tmpbnsam7rv', '--error-file', '/tmp/tmpf1l0jce2']
[2022-04-05 21:15:05,016] {standard_task_runner.py:77} INFO - Job 29: Subtask hook_task
[2022-04-05 21:15:05,054] {logging_mixin.py:109} INFO - Running <TaskInstance: hook_dag.hook_task manual__2022-04-05T21:14:01.741481+00:00 [running]> on host 13210251e6a6
[2022-04-05 21:15:05,090] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hook_dag
AIRFLOW_CTX_TASK_ID=hook_task
AIRFLOW_CTX_EXECUTION_DATE=2022-04-05T21:14:01.741481+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-05T21:14:01.741481+00:00
[2022-04-05 21:15:05,097] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-05 21:15:05,101] {python.py:175} INFO - Done. Returned value was: [(1, 'Max', 'Dog', datetime.date(2018, 7, 5), 'Jane'), (2, 'Susie', 'Cat', datetime.date(2019, 5, 1), 'Phil'), (3, 'Lester', 'Hamster', datetime.date(2020, 6, 23), 'Lily'), (4, 'Quincy', 'Parrot', datetime.date(2013, 8, 11), 'Anne')]
[2022-04-05 21:15:05,106] {xcom.py:448} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2022-04-05 21:15:05,106] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2151, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 155, in set
    value=cls.serialize_value(value),
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 445, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
[2022-04-05 21:15:05,115] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=hook_dag, task_id=hook_task, execution_date=20220405T211401, start_date=20220405T211504, end_date=20220405T211505
[2022-04-05 21:15:05,124] {standard_task_runner.py:92} ERROR - Failed to execute job 29 for task hook_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2151, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 155, in set
    value=cls.serialize_value(value),
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 445, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
[2022-04-05 21:15:05,147] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-05 21:15:05,233] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
