[2022-04-19 09:31:24,471] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: hook_dag.log_start manual__2022-04-19T09:30:20.848353+00:00 [queued]>
[2022-04-19 09:31:24,478] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: hook_dag.log_start manual__2022-04-19T09:30:20.848353+00:00 [queued]>
[2022-04-19 09:31:24,478] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-19 09:31:24,478] {taskinstance.py:1244} INFO - Starting attempt 2 of 2
[2022-04-19 09:31:24,478] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-19 09:31:24,486] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): log_start> on 2022-04-19 09:30:20.848353+00:00
[2022-04-19 09:31:24,490] {standard_task_runner.py:52} INFO - Started process 1941 to run task
[2022-04-19 09:31:24,492] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'hook_dag', 'log_start', 'manual__2022-04-19T09:30:20.848353+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/hook_dag.py', '--cfg-path', '/tmp/tmpmoww00zc', '--error-file', '/tmp/tmplz65beyh']
[2022-04-19 09:31:24,493] {standard_task_runner.py:77} INFO - Job 167: Subtask log_start
[2022-04-19 09:31:24,530] {logging_mixin.py:109} INFO - Running <TaskInstance: hook_dag.log_start manual__2022-04-19T09:30:20.848353+00:00 [running]> on host 22e04adb6bfa
[2022-04-19 09:31:24,553] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1423, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2011, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1061, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1074, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1108, in render_template
    template = jinja_env.get_template(content)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./template/sql/log_start.sql
[2022-04-19 09:31:24,562] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=hook_dag, task_id=log_start, execution_date=20220419T093020, start_date=20220419T093124, end_date=20220419T093124
[2022-04-19 09:31:24,570] {standard_task_runner.py:92} ERROR - Failed to execute job 167 for task log_start
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1423, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2011, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1061, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1074, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1108, in render_template
    template = jinja_env.get_template(content)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./template/sql/log_start.sql
[2022-04-19 09:31:24,584] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-19 09:31:24,612] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
