[2022-04-28 15:42:56,205] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: cso_2295_ipo_2_cso_bd.py.log_sensor1 manual__2022-04-28T15:42:54.659811+00:00 [queued]>
[2022-04-28 15:42:56,216] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: cso_2295_ipo_2_cso_bd.py.log_sensor1 manual__2022-04-28T15:42:54.659811+00:00 [queued]>
[2022-04-28 15:42:56,217] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 15:42:56,217] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-04-28 15:42:56,217] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 15:42:56,232] {taskinstance.py:1264} INFO - Executing <Task(SqlSensor): log_sensor1> on 2022-04-28 15:42:54.659811+00:00
[2022-04-28 15:42:56,238] {standard_task_runner.py:52} INFO - Started process 21397 to run task
[2022-04-28 15:42:56,240] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cso_2295_ipo_2_cso_bd.py', 'log_sensor1', 'manual__2022-04-28T15:42:54.659811+00:00', '--job-id', '1393', '--raw', '--subdir', 'DAGS_FOLDER/cso_2295/cso_2295_ipo_2_cso_bd.py', '--cfg-path', '/tmp/tmpoeu68kq7', '--error-file', '/tmp/tmpp89vivrj']
[2022-04-28 15:42:56,241] {standard_task_runner.py:77} INFO - Job 1393: Subtask log_sensor1
[2022-04-28 15:42:56,288] {logging_mixin.py:109} INFO - Running <TaskInstance: cso_2295_ipo_2_cso_bd.py.log_sensor1 manual__2022-04-28T15:42:54.659811+00:00 [running]> on host 0936e4a14e76
[2022-04-28 15:42:56,353] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cso_2295_ipo_2_cso_bd.py
AIRFLOW_CTX_TASK_ID=log_sensor1
AIRFLOW_CTX_EXECUTION_DATE=2022-04-28T15:42:54.659811+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-28T15:42:54.659811+00:00
[2022-04-28 15:42:56,367] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-28 15:42:56,429] {sql.py:98} INFO - Poking: select case when q = 'true' then 1 else 0 end as q from  (
	select case when count(id)=0 then 'true' else 'false' end as q
	from list_flow_log
	where object_flow = 0 and status = 1
) t1; (with parameters None)
[2022-04-28 15:42:56,443] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-28 15:43:56,518] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-28 15:43:56,561] {sql.py:98} INFO - Poking: select case when q = 'true' then 1 else 0 end as q from  (
	select case when count(id)=0 then 'true' else 'false' end as q
	from list_flow_log
	where object_flow = 0 and status = 1
) t1; (with parameters None)
[2022-04-28 15:43:56,567] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-28 15:44:56,652] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-28 15:44:56,764] {sql.py:98} INFO - Poking: select case when q = 'true' then 1 else 0 end as q from  (
	select case when count(id)=0 then 'true' else 'false' end as q
	from list_flow_log
	where object_flow = 0 and status = 1
) t1; (with parameters None)
[2022-04-28 15:44:56,769] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-28 15:45:23,089] {local_task_job.py:212} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-04-28 15:45:23,090] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 21397. PIDs of all processes in the group: [21397]
[2022-04-28 15:45:23,091] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 21397
[2022-04-28 15:45:23,091] {taskinstance.py:1413} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-04-28 15:45:23,147] {process_utils.py:70} INFO - Process psutil.Process(pid=21397, status='terminated', exitcode=0, started='15:42:56') (21397) terminated with exit code 0
[2022-04-28 15:45:23,171] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-28 15:45:23,176] {dbapi.py:225} INFO - Running statement: update list_flow_log
                set t_end=NOW(), status=3, code_error=3, comment = '*Task*: log_sensor1'
                where id = None;, parameters: None
[2022-04-28 15:45:23,177] {taskinstance.py:1582} ERROR - Error when executing on_failure_callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1580, in _run_finished_callback
    task.on_failure_callback(context)
  File "/opt/airflow/dags/cso_2295/cso_2295_ipo_2_cso_bd.py", line 57, in task_failure_log
    return log_err_dag.execute(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "none" does not exist
LINE 3:                 where id = None;
                                   ^

